config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


  #home
  root 'home#index'
  get 'home/index'

  get 'contact', to: 'home#contact'
  get 'login', to: 'home#login'
  get 'gallery_cat', to: 'home#gallery_cat'
  get 'gallery_dog', to: 'home#gallery_dog'


  #admin
  get '/admin/index', to: 'admin#index'
  get '/admin/gallery_cat_admin', to: 'admin#gallery_cat_admin'
  get '/admin/gallery_dog_admin', to: 'admin#gallery_dog_admin'

  namespace :admin do
    resources :cats, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :dogs, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  #user
  get '/user/index', to: 'user#index'
  get '/user/contact', to: 'user#contact'
  get '/user/gallery_cat_user', to: 'user#gallery_cat_user'
  get '/user/gallery_dog_user', to: 'user#gallery_dog_user'
  get '/dogs/:id/adopt', to: 'dogs#adopt', as: 'adopt_dog'
  get '/cats/:id/adopt', to: 'cats#adopt', as: 'adopt_cat'



  resources :cats do
    member do
      post 'adopt'
    end
  end

  resources :dogs do
    member do
      post 'adopt'
    end
  end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/admin/gallery_cat_admin.html.erb
<style>
   body {
      font-family: 'Arial', sans-serif;
      background-color: #f8f9fa;
    }
    .navbar-brand {
      font-weight: bold;
      display: flex;
      align-items: center;
    }
    .navbar-brand img {
      max-height: 40px; /* Ustaw maksymalną wysokość obrazu */
      margin-right: 10px;
      margin-left: 10px;
    }
    .nav-link {
      color: #d4a5e2 !important; /* Jasno fioletowy kolor */
    }
    .nav-link:hover {
      color: #9b59b6 !important; /* Ciemno fioletowy kolor */
    }
    .container {
      background: #ffffff;
      padding: 10px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    h1, h2 {
      color: #333;
    }
    .btn-light {
      background-color: #007bff;
      color: #fff;
    }
    .btn-light:hover {
      background-color: #0056b3;
      color: #fff;
    }

  </style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= admin_index_path %>"><%= image_tag "ikona.png", alt: "Ikona"%> Adoptuj Przyjaciela</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= admin_index_path %>">Home</a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbolinks="false">
            Galeria zwierząt
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= admin_gallery_cat_admin_path %>">Koty</a></li>
            <li><a class="dropdown-item" href="<%= admin_gallery_dog_admin_path %>">Psy</a></li>
          </ul>
        </li>
    </ul>
  </div>
</nav>


<div class="container">
<h1>Poznaj nasze kotki do adopcji &#128049;&#128156;! </h1>

  <div class="row">

    <div class="col-sm-3 mb-3 mb-sm-3">
    <div class="card" style="width: 18rem;">
        <%= image_tag("cat1.png", alt: "Cat1") %>
        <div class="card-body">
        <h5 class="card-title">Łapka</h5>
        <p class="card-text">Łapka to przyjanzna kotka, która szuka nowego domu.</p>
        <center><a href="#" class="btn btn-secondary">Szczegóły</a> <a href="#" class="btn btn-danger">Usuń</a></center>
        </div>
    </div>
    </div>

    <div class="col-sm-3">
    <div class="card" style="width: 18rem;">
        <%= image_tag("cat1.png", alt: "Cat1") %>
        <div class="card-body">
        <h5 class="card-title">Łapka</h5>
        <p class="card-text">Łapka to przyjanzna kotka, która szuka nowego domu.</p>
        <center><a href="#" class="btn btn-secondary">Szczegóły</a> <a href="#" class="btn btn-danger">Usuń</a></center>
        </div>
    </div>
    </div>

     <div class="col-sm-3">
    <div class="card" style="width: 18rem;">
        <%= image_tag("cat1.png", alt: "Cat1") %>
        <div class="card-body">
        <h5 class="card-title">Łapka</h5>
        <p class="card-text">Łapka to przyjanzna kotka, która szuka nowego domu.</p>
        <center><a href="#" class="btn btn-secondary">Szczegóły</a> <a href="#" class="btn btn-danger">Usuń</a></center>
        </div>
    </div>
    </div>

     <div class="col-sm-3">
    <div class="card" style="width: 18rem;">
        <%= image_tag("cat1.png", alt: "Cat1") %>
        <div class="card-body">
        <h5 class="card-title">Łapka</h5>
        <p class="card-text">Łapka to przyjanzna kotka, która szuka nowego domu.</p>
        <center><a href="#" class="btn btn-secondary">Szczegóły</a> <a href="#" class="btn btn-danger">Usuń</a></center>
        </div>
    </div>
    </div>

     <div class="col-sm-3">
    <div class="card" style="width: 18rem;">
        <%= image_tag("cat1.png", alt: "Cat1") %>
        <div class="card-body">
        <h5 class="card-title">Łapka</h5>
        <p class="card-text">Łapka to przyjanzna kotka, która szuka nowego domu.</p>
        <center><a href="#" class="btn btn-secondary">Szczegóły</a> <a href="#" class="btn btn-danger">Usuń</a></center>
        </div>
    </div>
    </div>

     <div class="col-sm-3">
    <div class="card" style="width: 18rem;">
        <%= image_tag("cat1.png", alt: "Cat1") %>
        <div class="card-body">
        <h5 class="card-title">Łapka</h5>
        <p class="card-text">Łapka to przyjanzna kotka, która szuka nowego domu.</p>
        <center><a href="#" class="btn btn-secondary">Szczegóły</a> <a href="#" class="btn btn-danger">Usuń</a></center>
        </div>
    </div>
    </div>

     <div class="col-sm-3">
    <div class="card" style="width: 18rem;">
        <%= image_tag("cat1.png", alt: "Cat1") %>
        <div class="card-body">
        <h5 class="card-title">Łapka</h5>
        <p class="card-text">Łapka to przyjanzna kotka, która szuka nowego domu.</p>
        <center><a href="#" class="btn btn-secondary">Szczegóły</a> <a href="#" class="btn btn-danger">Usuń</a></center>
        </div>
    </div>
    </div>

     <div class="col-sm-3">
    <div class="card" style="width: 18rem;">
        <%= image_tag("cat1.png", alt: "Cat1") %>
        <div class="card-body">
        <h5 class="card-title">Łapka</h5>
        <p class="card-text">Łapka to przyjanzna kotka, która szuka nowego domu.</p>
        <center><a href="#" class="btn btn-secondary">Szczegóły</a> <a href="#" class="btn btn-danger">Usuń</a></center>
        </div>
    </div>
    </div>




    

    
  </div>

    
</div>

app/views/admin/gallery_dog_admin.html.erb
<style>
   body {
      font-family: 'Arial', sans-serif;
      background-color: #f8f9fa;
    }
    .navbar-brand {
      font-weight: bold;
      display: flex;
      align-items: center;
    }
    .navbar-brand img {
      max-height: 40px; /* Ustaw maksymalną wysokość obrazu */
      margin-right: 10px;
      margin-left: 10px;
    }
    .nav-link {
      color: #d4a5e2 !important; /* Jasno fioletowy kolor */
    }
    .nav-link:hover {
      color: #9b59b6 !important; /* Ciemno fioletowy kolor */
    }
    .container {
      background: #ffffff;
      padding: 10px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    h1, h2 {
      color: #333;
    }
    .btn-light {
      background-color: #007bff;
      color: #fff;
    }
    .btn-light:hover {
      background-color: #0056b3;
      color: #fff;
    }

  </style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= admin_index_path %>"><%= image_tag "ikona.png", alt: "Ikona"%> Adoptuj Przyjaciela</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= admin_index_path %>">Home</a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbolinks="false">
            Galeria zwierząt
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= admin_gallery_cat_admin_path %>">Koty</a></li>
            <li><a class="dropdown-item" href="<%= admin_gallery_dog_admin_path %>">Psy</a></li>
          </ul>
        </li>
    </ul>
  </div>
</nav>


<div class="container">
<center><h1>Poznaj nasze pieski do adopcji &#128054;&#128156;! </h1></center>
<center><h3> Dodaj nowego psa <a href="<%= new_dog_path %>" class="btn btn-secondary">Dodaj</a></h2></center>


  <div class="row">
    <% @dogs.each do |dog| %>
      <div class="col-sm-3 mb-3">
        <div class="card" style="width: 18rem;">
          <% if dog.image.attached? %>
            <%= image_tag dog.image, class: 'card-img-top', alt: dog.name %>
          <% else %>
            <%= image_tag 'default_dog.png', class: 'card-img-top', alt: 'Default Dog' %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= dog.name %></h5>
            <p class="card-text"><%= dog.description %></p>
            <center>
            <%= link_to 'Szczegóły', dog_path(dog), class: 'btn btn-secondary' %>

            <%= form_with model: dog, url: dog_path(dog), method: :delete, local: true do |form| %>
              <%= form.submit 'Usuń', class: 'btn btn-danger', data: { confirm: 'Czy na pewno chcesz usunąć tego psa?' } %>
            <% end %>
          </center>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/index.html.erb
<style>
   body {
      font-family: 'Arial', sans-serif;
      background-color: #f8f9fa;
    }
    .navbar-brand {
      font-weight: bold;
      display: flex;
      align-items: center;
    }
    .navbar-brand img {
      max-height: 40px; /* Ustaw maksymalną wysokość obrazu */
      margin-right: 10px;
      margin-left: 10px;
    }
    .nav-link {
      color: #d4a5e2 !important; /* Jasno fioletowy kolor */
    }
    .nav-link:hover {
      color: #9b59b6 !important; /* Ciemno fioletowy kolor */
    }
    .container {
      background: #ffffff;
      padding: 10px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    h1, h2 {
      color: #333;
    }
    .btn-light {
      background-color: #007bff;
      color: #fff;
    }
    .btn-light:hover {
      background-color: #0056b3;
      color: #fff;
    }

  </style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= admin_index_path %>"><%= image_tag "ikona.png", alt: "Ikona"%> Adoptuj Przyjaciela</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= admin_index_path %>">Home <span class="sr-only">(aktualnie)</span></a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbolinks="false">
            Galeria zwierząt
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= admin_gallery_cat_admin_path %>">Koty</a></li>
            <li><a class="dropdown-item" href="<%= admin_gallery_dog_admin_path %>">Psy</a></li>
          </ul>
        </li>
    </ul>
  </div>
</nav>


<div class="container">
  <div class="row">

    <div class="col-md-6">
      <h1>Witaj Administratorze! &#129392; </h1>
        <div class="card bg-light mb-3" style="max-width: 35rem;">
        <div class="card-header">&#128049; Twoje zadania: </div>
        <div class="card-body">
        <p class="card-text">Możesz dodawać nowe zwierzaki do galerii oraz usuwać profile tych, które znalzły już nowy dom.</p>
        </div>
        </div>

        <div class="card bg-light mb-3" style="max-width: 35rem;">
        <div class="card-header">&#128054; Nasza misja: </div>
        <div class="card-body">
        <p class="card-text">Możesz edytować opisy zwierzaków, które czekają na nowy dom.</p>
        </div>
        </div>

        <%= form_tag(destroy_user_session_path, method: :delete) do %>
        <center><%= submit_tag "Wyloguj", class: "btn btn-outline-danger", style: "font-size:30px" %></center>
        <% end %>

    </div>

    <div class="col-md-5 text-right">
      <%= image_tag("admin.png", alt: "Logo", class: "rounded-image") %>
    </div>
  </div>

    
</div>