config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


  #home
  root 'home#index'
  get 'home/index'

  get 'contact', to: 'home#contact'
  get 'login', to: 'home#login'
  get 'gallery_cat', to: 'home#gallery_cat'
  get 'gallery_dog', to: 'home#gallery_dog'


  #admin
  get '/admin/index', to: 'admin#index'
  get '/admin/gallery_cat_admin', to: 'admin#gallery_cat_admin'
  get '/admin/gallery_dog_admin', to: 'admin#gallery_dog_admin'

  namespace :admin do
    resources :cats, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :dogs, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  #user
  get '/user/index', to: 'user#index'
  get '/user/contact', to: 'user#contact'
  get '/user/gallery_cat_user', to: 'user#gallery_cat_user'
  get '/user/gallery_dog_user', to: 'user#gallery_dog_user'
  get '/dogs/:id/adopt', to: 'dogs#adopt', as: 'adopt_dog'
  get '/cats/:id/adopt', to: 'cats#adopt', as: 'adopt_cat'



  resources :cats do
    member do
      post 'adopt'
    end
  end

  resources :dogs do
    member do
      post 'adopt'
    end
  end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :role, presence: true, inclusion: { in: %w[user admin] }

  has_many :adoptions
  has_many :adopted_dogs, through: :adoptions, source: :dog
  has_many :adopted_cats, through: :adoptions, source: :cat

  def admin?
    role == 'admin'
    
  end
       
  def user?
    role == 'user'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
  
  def contact
  
  end

  def gallery_cat_user
    @cats = Cat.all
  
  end

  def gallery_dog_user
    @dogs = Dog.all
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    super do |resource|
      if User.count == 1
        resource.role = 'admin'
        resource.save
      end
    end
  end


  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/contact.html.erb
<style>
    body {
      font-family: 'Arial', sans-serif;
      background-color: #f8f9fa;
    }
    .navbar-brand {
      font-weight: bold;
      display: flex;
      align-items: center;
    }
    .navbar-brand img {
      max-height: 40px; /* Ustaw maksymalną wysokość obrazu */
      margin-right: 10px;
      margin-left: 10px;
    }
    .nav-link {
      color: #d4a5e2 !important; /* Jasno fioletowy kolor */
    }
    .nav-link:hover {
      color: #9b59b6 !important; /* Ciemno fioletowy kolor */
    }
    .container {
      background: #ffffff;
      padding: 10px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    h1, h2 {
      color: #333;
    }
    .btn-light {
      background-color: #007bff;
      color: #fff;
    }
    .btn-light:hover {
      background-color: #0056b3;
      color: #fff;
    }
    .rounded-image {
      width: 50%;
      height: auto;
      border-radius: 8px;
      margin-bottom: 20px;
    }
  </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= user_index_path %>"><%= image_tag "ikona.png", alt: "Ikona"%> Adoptuj Przyjaciela</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= user_index_path %>">Home</a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbolinks="false">
            Galeria zwierząt
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= user_gallery_cat_user_path %>">Koty</a></li>
            <li><a class="dropdown-item" href="<%= user_gallery_dog_user_path %>">Psy</a></li>
          </ul>
        </li>
      <li class="nav-item active">
        <a class="nav-link" href="contact.html">Kontakt <span class="sr-only">(aktualnie)</span></a>
      </li>
    </ul>
  </div>
</nav>

<div class="container mt-5">
  <h1>Kontakt</h1>
  <p>Skontaktuj się z nami, aby uzyskać więcej informacji o naszych podopiecznych lub umówić się na spotkanie adopcyjne.</p>
  
  <div class="row">
    <div class="col-md-5">
      <h2>Dane kontaktowe</h2>
      <p><strong>Adoptuj Przyjaciela</strong><br>
      ul. Przyjacielska 123<br>
      00-000 Miastowo<br>
      Tel: 123-456-789<br>
      Email: kontakt@adoptujprzyjaciela.pl</p>
      <center><%= image_tag "contact.png", alt: "Kontakt", class: "rounded-image" %> </center>
    </div>



    <div class="col-md-5">
      <h2>Formularz kontaktowy</h2>
      <form>
        <div class="form-group">
          <label for="name">Imię i nazwisko</label>
          <input type="text" class="form-control" id="name" required>
        </div>
        <div class="form-group">
          <label for="email">Adres email</label>
          <input type="email" class="form-control" id="email" required>
        </div>
        <div class="form-group">
          <label for="message">Wiadomość</label>
          <textarea class="form-control" id="message" rows="5" required></textarea>
        </div>
        <button type="submit" class="btn btn-outline-secondary">Wyślij</button>
      </form>
    </div>
  </div>
</div>

app/views/user/gallery_cat_user.html.erb
<style>
   body {
      font-family: 'Arial', sans-serif;
      background-color: #f8f9fa;
    }
    .navbar-brand {
      font-weight: bold;
      display: flex;
      align-items: center;
    }
    .navbar-brand img {
      max-height: 40px; /* Ustaw maksymalną wysokość obrazu */
      margin-right: 10px;
      margin-left: 10px;
    }
    .nav-link {
      color: #d4a5e2 !important; /* Jasno fioletowy kolor */
    }
    .nav-link:hover {
      color: #9b59b6 !important; /* Ciemno fioletowy kolor */
    }
    .container {
      background: #ffffff;
      padding: 10px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    h1, h2 {
      color: #333;
    }
    .btn-light {
      background-color: #007bff;
      color: #fff;
    }
    .btn-light:hover {
      background-color: #0056b3;
      color: #fff;
    }

    .flash {
      padding: 10px;
      margin: 10px 0;
      border-radius: 5px;
    }
    .flash.notice {
      background-color: #d4edda;
      color: #155724;
      border: 1px solid #c3e6cb;
    }
    .flash.alert {
      background-color: #f8d7da;
      color: #721c24;
      border: 1px solid #f5c6cb;
    }

  </style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= user_index_path %>"><%= image_tag "ikona.png", alt: "Ikona"%> Adoptuj Przyjaciela</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= user_index_path %>">Home</a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbolinks="false">
            Galeria zwierząt
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= user_gallery_cat_user_path %>">Koty</a></li>
            <li><a class="dropdown-item" href="<%= user_gallery_dog_user_path %>">Psy</a></li>
          </ul>
        </li>
      <li class="nav-item">
        <a class="nav-link" href="contact.html">Kontakt</a>
      </li>
    </ul>
  </div>
</nav>


<div class="container">
  <% if flash[:notice] %>
    <div class="flash notice"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
    <div class="flash alert"><%= flash[:alert] %></div>
  <% end %>


<h1>Poznaj nasze kotki do adopcji &#128049;&#128156;! </h1>

  <div class="container mt-5">
  <div class="row">
    <% @cats.each do |cat| %>
      <div class="col-sm-3 mb-3">
        <div class="card" style="width: 18rem;">
          <% if cat.image.attached? %>
            <%= image_tag cat.image, class: 'card-img-top', alt: cat.name %>
          <% else %>
            <%= image_tag 'default_cat.png', class: 'card-img-top', alt: 'Default Cat' %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= cat.name %></h5>
            <p class="card-text"><%= cat.description %></p>
            <p class="card-text">Wirtualnie zaadoptowany przez <%= cat.adopters.count %> użytkowników</p>
            <center>
              <%= link_to 'Szczegóły', cat_path(cat), class: 'btn btn-secondary' %>
              <%= link_to 'Zaadoptuj', adopt_cat_path(cat), method: :post, class: 'btn btn-success' %>
            </center>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/user/gallery_dog_user.html.erb
<style>
   body {
      font-family: 'Arial', sans-serif;
      background-color: #f8f9fa;
    }
    .navbar-brand {
      font-weight: bold;
      display: flex;
      align-items: center;
    }
    .navbar-brand img {
      max-height: 40px; /* Ustaw maksymalną wysokość obrazu */
      margin-right: 10px;
      margin-left: 10px;
    }
    .nav-link {
      color: #d4a5e2 !important; /* Jasno fioletowy kolor */
    }
    .nav-link:hover {
      color: #9b59b6 !important; /* Ciemno fioletowy kolor */
    }
    .container {
      background: #ffffff;
      padding: 10px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    h1, h2 {
      color: #333;
    }
    .btn-light {
      background-color: #007bff;
      color: #fff;
    }
    .btn-light:hover {
      background-color: #0056b3;
      color: #fff;
    }
    .flash {
      padding: 10px;
      margin: 10px 0;
      border-radius: 5px;
    }
    .flash.notice {
      background-color: #d4edda;
      color: #155724;
      border: 1px solid #c3e6cb;
    }
    .flash.alert {
      background-color: #f8d7da;
      color: #721c24;
      border: 1px solid #f5c6cb;
    }
  </style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= user_index_path %>"><%= image_tag "ikona.png", alt: "Ikona"%> Adoptuj Przyjaciela</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= user_index_path %>">Home</a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbolinks="false">
            Galeria zwierząt
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= user_gallery_cat_user_path %>">Koty</a></li>
            <li><a class="dropdown-item" href="<%= user_gallery_dog_user_path %>">Psy</a></li>
          </ul>
        </li>
      <li class="nav-item">
        <a class="nav-link" href="contact.html">Kontakt</a>
      </li>
    </ul>
  </div>
</nav>

<div class="container">
  <% if flash[:notice] %>
    <div class="flash notice"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
    <div class="flash alert"><%= flash[:alert] %></div>
  <% end %>

  <h1>Poznaj nasze pieski do adopcji &#128054;&#128156;! </h1>

  <div class="container mt-5">
    <div class="row">
      <% @dogs.each do |dog| %>
        <div class="col-sm-3 mb-3">
          <div class="card" style="width: 18rem;">
            <% if dog.image.attached? %>
              <%= image_tag dog.image, class: 'card-img-top', alt: dog.name %>
            <% else %>
              <%= image_tag 'default_dog.png', class: 'card-img-top', alt: 'Default Dog' %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= dog.name %></h5>
              <p class="card-text"><%= dog.description %></p>
              <p class="card-text">Wirtualnie zaadoptowany przez <%= dog.adopters.count %> użytkowników</p>
              <center>
                <%= link_to 'Szczegóły', dog_path(dog), class: 'btn btn-secondary' %>
                <%= link_to 'Zaadoptuj', adopt_dog_path(dog), method: :post, class: 'btn btn-success' %>
              </center>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user/index.html.erb
<style>
   body {
      font-family: 'Arial', sans-serif;
      background-color: #f8f9fa;
    }
    .navbar-brand {
      font-weight: bold;
      display: flex;
      align-items: center;
    }
    .navbar-brand img {
      max-height: 40px; /* Ustaw maksymalną wysokość obrazu */
      margin-right: 10px;
      margin-left: 10px;
    }
    .nav-link {
      color: #d4a5e2 !important; /* Jasno fioletowy kolor */
    }
    .nav-link:hover {
      color: #9b59b6 !important; /* Ciemno fioletowy kolor */
    }
    .container {
      background: #ffffff;
      padding: 10px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    h1, h2 {
      color: #333;
    }
    .btn-light {
      background-color: #007bff;
      color: #fff;
    }
    .btn-light:hover {
      background-color: #0056b3;
      color: #fff;
    }

      .flash {
      padding: 10px;
      margin: 10px 0;
      border-radius: 5px;
    }
    .flash.notice {
      background-color: #d4edda;
      color: #155724;
      border: 1px solid #c3e6cb;
    }
    .flash.alert {
      background-color: #f8d7da;
      color: #721c24;
      border: 1px solid #f5c6cb;
    }

  </style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= user_index_path %>"><%= image_tag "ikona.png", alt: "Ikona"%> Adoptuj Przyjaciela</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= user_index_path %>">Home <span class="sr-only">(aktualnie)</span></a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbolinks="false">
            Galeria zwierząt
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= user_gallery_cat_user_path %>">Koty</a></li>
            <li><a class="dropdown-item" href="<%= user_gallery_dog_user_path %>">Psy</a></li>
          </ul>
        </li>
      <li class="nav-item">
        <a class="nav-link" href="contact.html">Kontakt</a>
      </li>
    </ul>
  </div>
</nav>


<div class="container">
  <div class="row">

    <div class="col-md-6">
      <h1>Witaj Użytkowniku! &#129392; </h1>
        <div class="card bg-light mb-3" style="max-width: 40rem;">
        <div class="card-header">&#128049; Wirtualna adopcja: </div>
        <div class="card-body">
        <p class="card-text">Jako zalogowany użytkownik możesz wirtulanie zaadoptować jednego z naszych przyjaciół. Po wirtualnej adopcji skontaktuje się z Tobą nasz administrator, który przekaże Ci numer konta, na który będziesz mógł wypłacić datek, który zostanie przeznaczony na zakup karmy dla Twojego wybranka.</p>
        </div>
        </div>

        <div class="card bg-light mb-3" style="max-width: 40rem;">
        <div class="card-header">&#128054; Prawdziwa adopcja: </div>
        <div class="card-body">
        <p class="card-text"> Możesz również zabrać jednego z naszych przyjaciół do swojego domu! Skontaktuj się z nami przez formularz kontaktowy!</p>
        </div>
        </div>

        <%= form_tag(destroy_user_session_path, method: :delete) do %>
        <center><%= submit_tag "Wyloguj", class: "btn btn-outline-danger", style: "font-size:30px" %></center>
        <% end %>

    </div>

    <div class="col-md-5 text-right">
      <%= image_tag("logo.png", alt: "Logo", class: "rounded-image") %>
    </div>
  </div>

    
</div>