config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


  #home
  root 'home#index'
  get 'home/index'

  get 'contact', to: 'home#contact'
  get 'login', to: 'home#login'
  get 'gallery_cat', to: 'home#gallery_cat'
  get 'gallery_dog', to: 'home#gallery_dog'


  #admin
  get '/admin/index', to: 'admin#index'
  get '/admin/gallery_cat_admin', to: 'admin#gallery_cat_admin'
  get '/admin/gallery_dog_admin', to: 'admin#gallery_dog_admin'

  namespace :admin do
    resources :cats, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :dogs, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  #user
  get '/user/index', to: 'user#index'
  get '/user/contact', to: 'user#contact'
  get '/user/gallery_cat_user', to: 'user#gallery_cat_user'
  get '/user/gallery_dog_user', to: 'user#gallery_dog_user'
  get '/dogs/:id/adopt', to: 'dogs#adopt', as: 'adopt_dog'
  get '/cats/:id/adopt', to: 'cats#adopt', as: 'adopt_cat'



  resources :cats do
    member do
      post 'adopt'
    end
  end

  resources :dogs do
    member do
      post 'adopt'
    end
  end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_one_attached :image
  has_many :adoptions, dependent: :destroy
  has_many :adopters, through: :adoptions, source: :user
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy, :adopt]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :adopt]
  before_action :check_admin, only: [:destroy] # Sprawdzenie, czy użytkownik jest adminem

  def index
    @cats = Cat.all
  end

  def show
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to admin_gallery_cat_admin_path, notice: 'Kot został pomyślnie utworzony.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cat.update(cat_params)
      redirect_to admin_gallery_cat_admin_path, notice: 'Kot został pomyślnie zaktualizowany.'
    else
      render :edit
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    
    # Usuń powiązane adopcje
    @cat.adoptions.destroy_all
    
    # Następnie usuń psa
    @cat.destroy
    
    redirect_to admin_gallery_cat_admin_path, notice: 'Kot został usunięty.'
  end

  def adopt
    @adoption = Adoption.new(cat: @cat, user: current_user)
  
    if @adoption.save
      redirect_to user_gallery_cat_user_path, notice: 'Zaadoptowałeś wirtualnie tego kota.'
    else
      redirect_to user_gallery_cat_user_path, alert: 'Zaadoptowłeś już tego kota'
    end
  end
  

  private

  def set_cat
    @cat = Cat.find(params[:id])
  end

  def cat_params
    params.require(:cat).permit(:name, :age, :description, :adopted, :image)
  end

  def check_admin
    unless current_user&.admin?
      redirect_to root_path, alert: 'Nie masz uprawnień do usunięcia tego kota.'
    end
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/adopt.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <% if @cat.image.attached? %>
          <%= image_tag @cat.image, class: 'card-img-top', alt: @cat.name %>
        <% else %>
          <%= image_tag 'default_cat.png', class: 'card-img-top', alt: 'Default Cat' %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title">Gratulacje!</h5>
          <p class="card-text">Właśnie zaadoptowałeś <%= @cat.name %>!</p>
          <%= link_to 'Powrót do galerii', user_gallery_cat_user_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cats/edit.html.erb
<style>
   body {
      font-family: 'Arial', sans-serif;
      background-color: #f8f9fa;
    }
    .navbar-brand {
      font-weight: bold;
      display: flex;
      align-items: center;
    }
    .navbar-brand img {
      max-height: 40px; /* Ustaw maksymalną wysokość obrazu */
      margin-right: 10px;
      margin-left: 10px;
    }
    .nav-link {
      color: #d4a5e2 !important; /* Jasno fioletowy kolor */
    }
    .nav-link:hover {
      color: #9b59b6 !important; /* Ciemno fioletowy kolor */
    }
    .container {
      background: #ffffff;
      padding: 10px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    h1, h2 {
      color: #333;
    }
    .btn-light {
      background-color: #007bff;
      color: #fff;
    }
    .btn-light:hover {
      background-color: #0056b3;
      color: #fff;
    }

  </style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= admin_index_path %>"><%= image_tag "ikona.png", alt: "Ikona"%> Adoptuj Przyjaciela</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= admin_index_path %>">Home <span class="sr-only">(aktualnie)</span></a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbolinks="false">
            Galeria zwierząt
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= admin_gallery_cat_admin_path %>">Koty</a></li>
            <li><a class="dropdown-item" href="<%= admin_gallery_dog_admin_path %>">Psy</a></li>
          </ul>
        </li>
    </ul>
  </div>
</nav>


<div class="container">
<h1> Edytuj szczegóły tego kota</h1>

    <%= form_with model: @cat, local: true, html: { class: 'needs-validation', novalidate: true } do |form| %>
        <% if @cat.errors.any? %>
            <div class="alert alert-danger">
            <h4 class="alert-heading"><%= pluralize(@cat.errors.count, "błąd") %> wystąpił(a) podczas próby zapisania kota:</h4>
            <ul>
            <% @cat.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
            </div>
        <% end %>

    <div class="form-floating mb-3">
        <%= form.text_field :name, class: 'form-control', id: 'name', placeholder: 'Imię' %>
        <%= form.label :name, 'Imię', class: 'form-label' %>
    </div>

    <div class="form-floating mb-3">
        <%= form.number_field :age, class: 'form-control', id: 'age', placeholder: 'Wiek' %>
        <%= form.label :age, 'Wiek', class: 'form-label' %>
    </div>

    <div class="form-floating mb-3">
        <%= form.text_area :description, class: 'form-control', id: 'description', placeholder: 'Opis', style: 'height: 100px;' %>
        <%= form.label :description, 'Opis', class: 'form-label' %>
    </div>

    <div class="form-check mb-3">
        <%= form.check_box :adopted, class: 'form-check-input', id: 'adopted' %>
        <%= form.label :adopted, 'Adoptowany', class: 'form-check-label' %>
    </div>

    <div class="actions">
        <center><%= form.submit "Zapisz", class: 'btn btn-success' %></center>
    </div>

    <% end %>

<center> <%= link_to 'Powrót', admin_gallery_cat_admin_path, class: 'btn btn-secondary mt-3' %> </center>
    
</div>

app/views/cats/index.html.erb
<h1>Lista Kotów</h1>

<% @cats.each do |cat| %>
  <p>
    <strong>Imię:</strong>
    <%= cat.name %><br>
    <strong>Wiek:</strong>
    <%= cat.age %><br>
    <strong>Opis:</strong>
    <%= cat.description %><br>
    <strong>Adoptowany:</strong>
    <%= cat.adopted ? "Tak" : "Nie" %>
    <strong>Wirtualnie zaadoptowany przez:</strong> <%= cat.adopters.count %> użytkowników<br>
    <% if user_signed_in? && !current_user.adopted_cats.include?(cat) %>
      <%= link_to 'Zaadoptuj', adopt_cat_path(@cat), method: :post, class: 'btn btn-success' %>
    <% end %>
  </p>
<% end %>

app/views/cats/new.html.erb
<style>
   body {
      font-family: 'Arial', sans-serif;
      background-color: #f8f9fa;
    }
    .navbar-brand {
      font-weight: bold;
      display: flex;
      align-items: center;
    }
    .navbar-brand img {
      max-height: 40px; /* Ustaw maksymalną wysokość obrazu */
      margin-right: 10px;
      margin-left: 10px;
    }
    .nav-link {
      color: #d4a5e2 !important; /* Jasno fioletowy kolor */
    }
    .nav-link:hover {
      color: #9b59b6 !important; /* Ciemno fioletowy kolor */
    }
    .container {
      background: #ffffff;
      padding: 10px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    h1, h2 {
      color: #333;
    }
    .btn-light {
      background-color: #007bff;
      color: #fff;
    }
    .btn-light:hover {
      background-color: #0056b3;
      color: #fff;
    }

  </style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= admin_index_path %>"><%= image_tag "ikona.png", alt: "Ikona"%> Adoptuj Przyjaciela</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= admin_index_path %>">Home <span class="sr-only">(aktualnie)</span></a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbolinks="false">
            Galeria zwierząt
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= admin_gallery_cat_admin_path %>">Koty</a></li>
            <li><a class="dropdown-item" href="<%= admin_gallery_dog_admin_path %>">Psy</a></li>
          </ul>
        </li>
    </ul>
  </div>
</nav>


<div class="container">
<h1>Dodaj nowego kota</h1>

    <%= form_with model: @cat, local: true, html: { class: 'needs-validation', novalidate: true } do |form| %>
        <% if @cat.errors.any? %>
            <div class="alert alert-danger">
            <h4 class="alert-heading"><%= pluralize(@cat.errors.count, "błąd") %> wystąpił(a) podczas próby zapisania kota:</h4>
            <ul>
            <% @cat.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
            </div>
        <% end %>

    <div class="form-floating mb-3">
        <%= form.file_field :image, class: 'form-control', id: 'image' %>
        <%= form.label :image, 'Zdjęcie', class: 'form-label' %>
    </div>

    <div class="form-floating mb-3">
        <%= form.text_field :name, class: 'form-control', id: 'name', placeholder: 'Imię' %>
        <%= form.label :name, 'Imię', class: 'form-label' %>
    </div>

    <div class="form-floating mb-3">
        <%= form.number_field :age, class: 'form-control', id: 'age', placeholder: 'Wiek' %>
        <%= form.label :age, 'Wiek', class: 'form-label' %>
    </div>

    <div class="form-floating mb-3">
        <%= form.text_area :description, class: 'form-control', id: 'description', placeholder: 'Opis', style: 'height: 100px;' %>
        <%= form.label :description, 'Opis', class: 'form-label' %>
    </div>

    <div class="form-check mb-3">
        <%= form.check_box :adopted, class: 'form-check-input', id: 'adopted' %>
        <%= form.label :adopted, 'Adoptowany', class: 'form-check-label' %>
    </div>

    <div class="actions">
        <center><%= form.submit "Zapisz", class: 'btn btn-success' %></center>
    </div>

    <% end %>

<center> <%= link_to 'Powrót', cats_path, class: 'btn btn-secondary mt-3' %> </center>
    
</div>

app/views/cats/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-5">
      <div class="card">
        <% if @cat.image.attached? %>
          <%= image_tag @cat.image, class: 'card-img-top', alt: @cat.name %>
        <% else %>
          <%= image_tag 'default_cat.png', class: 'card-img-top', alt: 'Default Cat' %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= @cat.name %></h5>
          <p class="card-text"><strong>Wiek:</strong> <%= @cat.age %> lat</p>
          <p class="card-text"><%= @cat.description %></p>
          <p class="card-text"><strong>Adoptowany przez:</strong> <%= @cat.adopters.count %> użytkowników</p>


            <!-- Link do powrotu warunkowo na podstawie roli użytkownika -->
            <center>
            <% if user_signed_in? %>
                <% if current_user.admin? %>
                <%= link_to 'Powrót', admin_gallery_cat_admin_path, class: 'btn btn-secondary' %>
                <% else %>
                <%= link_to 'Powrót', user_gallery_cat_user_path, class: 'btn btn-secondary' %>
                <% end %>
            <% else %>
                <%= link_to 'Powrót', gallery_cat_path, class: 'btn btn-secondary' %>
            <% end %>

            <% if user_signed_in? && current_user.admin? %>
                <%= link_to 'Edytuj', edit_cat_path(@cat), class: 'btn btn-primary' %>
            <% end %>
             </center>

            <center>
            
            </center>


        </div>
      </div>
    </div>
  </div>
</div>